var arr = [
    {
		"href":"/website/web_collect/movie/index.html",
		"cont":"movie"
	},
	{
		"href":"/website/web_collect/music/index.html",
		"cont":"music"
	},
    {
		"href":"/website/note/music.md",
		"cont":"music.md"
	},
    {
		"href":"/website/note/音乐家.md",
		"cont":"音乐家.md"
	},
    {
		"href":"/website/note/时间越来越快的原因.md",
		"cont":"时间越来越快的原因.md"
	},
	{
		"href":"https://hideip.network/",
		"cont":"web-proxy-online"
	},
	{
		"href":"https://macwk.cn/",
		"cont":"A-moive|mac-software"
	},
    {
		"href":"https://www.bmabk.com/",
		"cont":"A-moive|极客之音"
	},
	{
		"href":"https://stackblitz.com/",
		"cont":"StackBlitz| 在线 IDE"
	},
	{
		"href":"https://www.xue8nav.com/",
		"cont":"学吧导航"
	},
	{
		"href":"https://dalao.ru/",
		"cont":"元婴"
	},
	{
		"href":"https://www.zuoshipin.com/",
		"cont":"zuoshipin"
	},
	{
		"href":"https://jianwai.youdao.com/index/0",
		"cont":"srt字幕翻译"
	},
	{
		"href":"https://labs.heygen.com/guest/video-translate",
		"cont":"video-translate"
	},
	{
		"href":"https://aniwave.to/home",
		"cont":"aniwave"
	},
	{
		"href":"https://fmoviesz.to/home",
		"cont":"fmoviesz"
	},
	{
		"href":"https://mangafire.to/home",
		"cont":"mangafire"
	},
	{
		"href":"https://zorohd.to/home",
		"cont":"zorohd"
	},
	{
		"href":"https://cloudtts.com/",
		"cont":"文本阅读"
	},
	{
		"href":"https://ld246.com/",
		"cont":"链滴 - 记录生活，连接点滴"
	},
	{
		"href":"https://ld246.com/tag/vditor",
		"cont":"vditor"
	},
	{
		"href":"https://cotrans.touhou.ai/",
		"cont":"图片翻译"
	},
	{
		"href":"https://m.kekenet.com/",
		"cont":"可可英语"
	},

	{
		"href":"https://www.earthol.com/",
		"cont":"地球在线"
	},
	{
		"href":"https://redirect.invidious.io/",
		"cont":"redirect"
	},
	{
		"href":"https://www.5mku.com/",
		"cont":"吾名软件库"
	},
	{
		"href":"https://gs.colnago.icu/",
		"cont":"谷歌镜像站"
	},
	{
		"href":"https://www.xiaoermeizai.com/",
		"cont":"发现好应用"
	},
	{
		"href":"https://wiki.bqrdh.com/naming/great-name",
		"cont":"起名"
	},

	{
		"href":"https://tools.bqrdh.com/chess/",
		"cont":"象棋"
	},
	{
		"href":"https://tools.bqrdh.com/tetris/",
		"cont":"俄罗斯方块"
	},
	{
		"href":"https://tools.bqrdh.com/linux-command/",
		"cont":"linux命令搜索"
	},
	{
		"href":"https://dh.wjsou.com/",
		"cont":"AI聚合资源搜索引擎"
	},
	{
		"href":"https://mirror.js.org/",
		"cont":"mirror_google"
	},
	{
		"href":"https://aicodeconvert.com/",
		"cont":"AI Code Converter"
	},
	{
		"href":"https://caoniang.com/",
		"cont":"鸡盒导航"
	},
	{
		"href":"http://www.ixinqing.com/",
		"cont":"心晴网"
	},
	{
		"href":"https://www.zdic.net/",
		"cont":"漢典"
	},
	{
		"href":"https://open.163.com/",
		"cont":"网易公开课"
	},
	{
		"href":"https://www.s5t.com/",
		"cont":"搜网通"
	},
	{
		"href":"https://pdfdrive.to/",
		"cont":"PDFDrive"
	},
	{
		"href":"https://qread.xmsoushu.com/",
		"cont":"熊猫速读"
	},
	{
		"href":"https://xmsoushu.com/#/",
		"cont":"熊猫搜书"
	},
	{
		"href":"https://www.jiumodiary.com/",
		"cont":"鸠摩搜书"
	},
	{
		"href":"https://tophub.today/",
		"cont":"今日热榜"
	},
	{
		"href":"https://www.vqs.com/article/4425.html",
		"cont":"骑士下载"
	},
	{
		"href":"https://toolsdar.com/",
		"cont":"工具达人"
	},
	{
		"href":"https://www.bgrdh.com/",
		"cont":"办公导航"
	},
	{
		"href":"https://zbook.lol/",
		"cont":"zbook"
	},

	{
		"href":"https://lanrenao.com/",
		"cont":"懒人导航"
	},
	{
		"href":"https://www.watchtving.com/",
		"cont":"watchtving"
	},
	{
		"href":"https://www.bbwiner.com/",
		"cont":"bbwiner"
	},
	{
		"href":"https://sc.panda321.com/",
		"cont":"熊猫学术-Google scholar"
	},
	{
		"href":"https://developer.aliyun.com/mirror/?utm_content=g_1000303593",
		"cont":"阿里镜像站"
	},
	{
		"href":"https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/",
		"cont":"XAMPP"
	},
	{
		"href":"https://noisevip.cn/",
		"cont":"NOISE宝藏阁"
	},
	{
		"href":"http://www.quanben5.com/amp/",
		"cont":"免费小说"
	},
	{
		"href":"https://www.libvio.com/",
		"cont":"libvio.com"
	},
	{
		"href":"https://imyshare.com/",
		"cont":"精品资源导航"
	},
	{
		"href":"https://www.bqrdh.com/",
		"cont":"专业导航网站"
	},
	{
		"href":"http://guozhivip.com/",
		"cont":"果汁导航"
	},
	{
		"href":"https://www.zuh8.com/",
		"cont":"最U导航"
	},
	{
		"href":"https://36kdh.com/",
		"cont":"36K导航"
	},
	{
		"href":"https://www.zhil.cc",
		"cont":"知客导航"
	},
	{
		"href":"https://klyingshi.com/",
		"cont":"可乐导航"
	},
	{
		"href":"https://kkok.cc/",
		"cont":"壳壳博客"
	},
	{
		"href":"https://www.wangzhanchi.com/",
		"cont":"网站大全"
	},
	{
		"href":"https://ttdh.cn/",
		"cont":"天天导航"
	},
	{
		"href":"https://www.hohovod.com/",
		"cont":"hohovod"
	},
	{
		"href":"https://toolsdar.com/",
		"cont":"工具达人"
	},

	{
		"href":"https://myflixer.is/home",
		"cont":"myflixer"
	},
	{
		"href":"https://cddys.vip/",
		"cont":"cddys"
	},
	{
		"href":"https://toolai.io/zh/",
		"cont":"AI-TOOL"
	},
	{
		"href":"https://toolai.io",
		"cont":"AI-TOOL"
	},
	{
		"href":"https://adzhp.xyz/",
		"cont":"爱达杂货铺"
	},
	{
		"href":"https://rocumentaries.com/",
		"cont":"纪录片"
	},
	{
		"href":"https://www.zifumao.com/2440.html",
		"cont":"谷歌镜像站"
	},
	{
		"href":"https://www.22vd.com/75138.html",
		"cont":"谷歌镜像站"
	},
	{
		"href":"https://ppxzy.net/",
		"cont":"皮皮虾资源"
	},
	{
		"href":"https://www.24kdh.vip/",
		"cont":"24K导航"
	},
	{
		"href":"https://word-wind.pages.dev/",
		"cont":"word-wind"
	},
    {
		"href":"https://funletu.com/",
		"cont":"趣乐兔"
	},
    {
		"href":"https://www.englishclass101.com/",
		"cont":"englishclass101.com"
	},
	{
		"href":"https://www.bilibili.com/video/BV1Dk4y1q781/?spm_id_from=333.788.recommend_more_video.1&vd_source=19beb856dede8620770a18feaaf13ae2",
		"cont":"ted700"
	},
	{
		"href":"https://www.bilibili.com/video/BV1Pp4y1C7Rp/?spm_id_from=333.999.0.0&vd_source=19beb856dede8620770a18feaaf13ae2",
		"cont":"English Words for Every Day"
	},
	{
		"href":"https://www.bilibili.com/list/517809898?sid=2085216&spm_id_from=333.999.0.0&desc=1&oid=704709530&bvid=BV1AQ4y1s7LU",
		"cont":"English Word Choice"
	},
    {
        "href":"https://www.bilibili.com/video/BV124411G76C",
        "cont":"【英语日常口语合集】01-90（中英文字幕）"
    },
    {
        "href":"https://www.bilibili.com/video/BV1vE411d7ht",
        "cont":"【1000集全】英文有声书 英文故事 口语听力纯干货"
    },
    {
        "href":"https://www.bilibili.com/video/BV1Fb411g7g8",
        "cont":"【英语-合集】英文故事干货系列160集全"
    },
    {
        "href":"https://www.bilibili.com/video/BV1nE411G78r",
        "cont":"【经典美音】 口语听力210集全"
    },
    {
        "href":"https://www.bilibili.com/video/BV1tt411L7v7",
        "cont":"【英语-合集】跟着老外 说一口地道英音口语（75集全）"
    },
    {
        "href":"https://www.bilibili.com/video/BV12b41187gF",
        "cont":"【英音/合集】和Lucy一起学英语吧(01-150)【English with Lucy】"
    },
    {
        "href":"https://www.bilibili.com/video/BV1EE411y7tR",
        "cont":"【332集全】纯正英音 口语听力语法干货 English With Papa Lucy Emma"
    },
    {
        "href":"https://www.bilibili.com/video/BV194411w7SN",
        "cont":"【英语-合集】杜克大学女教授 精讲英文写作教程48集全"
    },
    {
        "href":"https://www.bilibili.com/video/BV1ZJ411778e",
        "cont":"【口语听力干货600集全 英文动画故事系列"
    },
    {
        "href":"https://www.bilibili.com/video/BV12E411879E",
        "cont":"【500集全】原汁原味 美国小学生的英语课"
    },
    {
        "href":"https://www.bilibili.com/video/BV1x7411j7ER",
        "cont":"【700集全】经典美音 美中小学教学原版教材精讲"
    },
    {
        "href":"https://www.bilibili.com/video/BV13E411x7i8",
        "cont":"【1000集全】原汁原味 美国儿童启蒙教育英语学习动画系列"
    },
    {
        "href":"https://www.bilibili.com/video/BV1DJ411S79k",
        "cont":"【300集全】英文动画 神话故事系列 English Fairy Tales"
    },
    {
        "href":"https://www.bilibili.com/video/BV1w4411W7s2",
        "cont":"【英语-合集】美国8岁女孩的美音朗读30集全"
    },
    {
        "href":"https://www.bilibili.com/video/BV14b41137rD",
        "cont":"【105集全】英文动画故事 史努比"
    },
    {
        "href":"https://www.bilibili.com/video/BV194411K7TC",
        "cont":"【英语-合集】少儿英语 English for Kids"
    },
    {
        "href":"https://www.bilibili.com/video/BV1Yb41117kR",
        "cont":"【《新概念英语》动画全集 【第一册】【第二册】【第三册】【第四册】"
    },
    {
        "href":"https://www.bilibili.com/video/BV1G44117744",
        "cont":"【英语-合集】英文动画故事93集全"
    },
    {
        "href":"https://www.bilibili.com/video/BV1f4411M71c",
        "cont":"【83集全】幼儿英语启蒙 儿童动画系列"
    },
    {
        "href":"https://www.bilibili.com/video/BV1e4411f7KR",
        "cont":"【英语-合集】英语口语听力（儿童英语） 48集全"
    },
    {
        "href":"https://www.bilibili.com/video/BV17t41177Ng",
        "cont":"【174集全】英语口语听力 情景对话动画系列"
    },
    {
        "href":"https://www.bilibili.com/video/BV1gx411o7My",
        "cont":"【392集全】Learn English via listening英语基础词汇学习"
    },
    {
        "href":"https://www.bilibili.com/video/BV1p441187yN",
        "cont":"【180集全】4千英语基本词汇（1-6册）"
    },
    {
        "href":"https://www.bilibili.com/video/BV1bJ411N7vU",
        "cont":"【185集全】口语听力干货 一分钟情景剧"
    },
    {
        "href":"https://www.bilibili.com/video/BV1bE411k78N",
        "cont":"【800集全】口语听力干货 English With Bob"
    },
    {
        "href":"https://www.bilibili.com/video/BV1BE411C7AR",
        "cont":"【447集全】口语听力语法纯干货  Actual English with Jennifer"
    },
    {
        "href":"https://www.bilibili.com/video/BV1X4411E7gF",
        "cont":"【170集全】经典美音 Alisha口语听力语法系列"
    },
    {
        "href":"https://www.bilibili.com/video/BV1aE411e7aB",
        "cont":"【210集全】纯正美音Alisha 口语听力语法 English Top Words"
    },
    {
        "href":"https://www.bilibili.com/video/BV1EJ411B75E",
        "cont":"【500集全】口语听力干货 English Like A Native"
    },
    {
        "href":"https://www.bilibili.com/video/BV1Hb411G7Gv",
        "cont":"【英语-合集】美式英语口语发音 Lisa美语教程（54集全）"
    },
    {
        "href":"https://zh.javascript.info/",
        "cont":"现代 JavaScript 教程"
    },
    {
        "href":"https://www.ixigua.com/channel/dianying/",
        "cont":"ixigua.com"
    },
    {
        "href":"https://crossub.xiaowude.com/srt/1020",
        "cont":"视频字幕工具，高效转换srt/lrc字幕，快速导入final cut pro / permiere"
    },
    {
        "href":"https://agent.kardel.xyz/",
        "cont":"字幕翻译"
    },
    {
        "href":"https://github.hscsec.cn/atelier-anchor/smiley-sans",
        "cont":"开源字体"
    },
    {
        "href":"https://tern.1c7.me/#/",
        "cont":"字幕翻译"
    },
    {
        "href":"https://www.deepl.com/translator/files",
        "cont":"DeepL-翻译"
    },
    {
        "href":"https://zh.editingtools.io/translate/",
        "cont":"translate"
    },
    {
        "href":"https://meta.appinn.net/t/topic/25323/1",
        "cont":"vovsoft-翻译"
    },
    {
        "href":"https://zhuanlan.zhihu.com/p/142234424",
        "cont":"翻译工具"
    },
    {
        "href":"https://invidious.asir.dev/channel/UCxXvigD355ALunI2mg8VU0Q/playlists",
        "cont":"How To In 5 Minutes—AI"
    },
    {
        "href":"https://moonvalley.ai/?via=aitoolsarena.com",
        "cont":"moonvalley"
    },
    {
        "href":"https://www.heygen.com/",
        "cont":"heygen-AI"
    },
    {
        "href":"https://hideip.network/",
        "cont":"web-proxy-online"
    },
    {
        "href":"https://www.gtyyj.com/",
        "cont":"GTYYJ·资源分享"
    },
    {
        "href":"https://www.midjourneyai.ai/zh-CN",
        "cont":"midjourney"
    },
    {
        "href":"https://www.nowcoder.com/exam/company",
        "cont":"牛客网公司真题"
    },
    {
        "href":"https://proxyium.com/",
        "cont":"free web proxy-youtube"
    },
    {
        "href":"https://plainproxies.com/resources/free-web-proxy",
        "cont":"free web proxy"
    },
    {
        "href":"https://e7m0rt4uzw.feishu.cn/wiki/OohrwqbhWi8WOCkO0DUcDwUZn4f",
        "cont":"AI绘画知识库"
    },
    {
        "href":"https://pudding.cool/",
        "cont":"pudding.cool/"
    },
    {
        "href":"https://programmercarl.com/",
        "cont":"代码随想录"
    },
    {
        "href":"https://stackblitz.com/",
        "cont":"stackblitz-在线编辑器"
    },
    {
        "href":"https://link.juejin.cn/?target=https%3A%2F%2Fstackblitz.com%2Fedit%2Fvitejs-vite-emryft%3Ffile%3Dsrc%252FApp.tsx",
        "cont":"React 使用Canvas绘制大数据表格"
    },
    {
        "href":"https://web.xn--xhqwov38c.com/aHR0cHM6Ly9naXRodWIuY29tL2hpZGVpcG5ldHdvcms=/hvtrs8%2F-wuw%2Crkgjt%2Ccmm%2Ccl%2Fdopuo%2F",
        "cont":"恩山论坛"
    },
    {
        "href":"https://chatgpt123.com/",
        "cont":"ChatGPT123 | ChatGPT导航站、资源站、中文社区"
    },
    {
        "href":"https://macwk.cn/",
        "cont":"MacWk - 精品mac软件下载"
    },
    {
        "href":"https://save.tube/",
        "cont":"youtube-download"
    },
    {
        "href":"http://movie.4kgod.cc/",
        "cont":"4kgod"
    },
    {
        "href":"https://liber3.eth.limo/#/",
        "cont":"书籍下载"
    },
    {
        "href":"http://www.53bk.com/Baokan/",
        "cont":"报刊"
    },
    {
        "href":"https://www.rustc.cloud/mac-install",
        "cont":"mac装机推荐"
    },
    {
        "href":"https://www.7sbook.com/",
        "cont":"传硕公版书"
    },
    {
        "href":"https://shuge.org/",
        "cont":"书格"
    },
    {
        "href":"https://kgbook.com/",
        "cont":"苦瓜书盘"
    },
    {
        "href":"https://sobooks.net/",
        "cont":"SoBook"
    },
    {
        "href":"https://yabook.org/",
        "cont":"雅书"
    },
    {
        "href":"https://freembook.com/",
        "cont":"FreemBook"
    },
    {
        "href":"https://zhiso.top/",
        "cont":"知搜"
    },
    {
        "href":"http://zxcs.me/",
        "cont":"知轩藏书"
    },
    {
        "href":"https://www.dalanmei.com/",
        "cont":"大蓝莓"
    },
    {
        "href":"https://www.freebookcentre.net/",
        "cont":"freebookcentre"
    },
    {
        "href":"http://r.ftqq.com/lean-side-bussiness/",
        "cont":"程序员如何优雅地做副业"
    },
    {
        "href":"https://excalidraw.com/",
        "cont":"开源虚拟手绘风格白板"
    },
    {
        "href":"https://ftqq.com/",
        "cont":"方糖气球"
    },
    {
        "href":"https://www.ziziys.com/",
        "cont":"子子影视"
    },
    {
        "href":"https://www.nodeseek.com/",
        "cont":"nodeseek"
    },
    {
        "href":"https://www.i3zh.com/",
        "cont":"i3综合社区"
    },
    {
        "href":"https://blog.tanglu.me/web-browser/",
        "cont":"tanglu"
    },
    {
        "href":"https://rp1.ssh.town/",
        "cont":"web-proxy-online"
    },
    {
        "href":"https://www.thesoulofwind.com/",
        "cont":"The Soul of Wind"
    },
    // 关键词：name:Therese; name:The Soul of Wind; note:Notability(iPad app)
    {
        "href":"https://www.youtube.com/channel/UCc1QflC90Nkf_SDBZwJScDQ",
        "cont":"studytee-Therese"
    },
    {
        "href":"https://gpt4all.io/index.html",
        "cont":"GPT4All-免费开源 LLM 聊天机器人 无需 GPU 或互联网"
    },
    {
        "href":"https://github.com/nomic-ai/gpt4all",
        "cont":"nomic-ai"
    },
    {
        "href":"https://fuliba2023.net/tivimate.html",
        "cont":"拯救网络电视，空壳软件Tivimate+范明明源"
    },
    {
        "href":"https://www.vectorpea.com/",
        "cont":"在线PhotoShop网页版"
    },
    {
        "href":"https://wallhaven.icu/",
        "cont":"好看的壁纸网站"
    },
    {
        "href":"https://www.yuque.com/wikidesign/vngzgk",
        "cont":"大厂AI实践"
    },
    {
        "href":"https://www.ciligege1.com/",
        "cont":"资源搜索"
    },
    {
        "href":"https://www.idmchina.net/",
        "cont":"IDM中文网-Internet Download Manager-IDM下载器"
    },
    {
        "href":"https://alist.lolicon.lol/",
        "cont":"花月喵梦是一个基于alist搭建的在线资源丰富的私人网盘"
    },
    {
        "href":"https://immersivetranslate.com/docs/sites/",
        "cont":"沉浸式翻译"
    },
    {
        "href":"https://nav.coolexe.com/",
        "cont":"阿酷导航"
    },
    {
        "href":"https://www.sharp.cn/node/1210",
        "cont":"SHARP-移动设备解决方案"
    },
    {
        "href":"https://nav.wsoso.com",
        "cont":"蓝点网址导航"
    },
    {
        "href":"http://www.biancheng.net/computer/software.html",
        "cont":"编程帮"
    },
    {
        "href":"http://www.codebaoku.com/",
        "cont":"编程宝库"
    },
    {
        "href":"https://bbs.yiove.com/",
        "cont":"Yiove.com"
    },
    {
        "href":"https://github.com/Meroser/IPTV",
        "cont":"Meroser-IPTV"
    },
    {
        "href":"https://yunyinghui.feishu.cn/docx/Q66RdH4lNoLW7nxSjXBcjcOtnod",
        "cont":"2024互联网知识地图最全合集"
    },
    {
        "href":"https://www.shukui.net/",
        "cont":"书葵网"
    },
    {
        "href":"https://www.3dmgame.com/",
        "cont":"3dgame"
    },
    {
        "href":"https://blog.fhmv.com/",
        "cont":"法海影视网"
    },
    {
        "href":"https://n.shawx.cn/",
        "cont":"N+导航"
    },
    {
        "href":"http://tool.mkblog.cn/",
        "cont":"工具箱"
    },
    {
        "href":"https://www.lovestu.com/",
        "cont":"Lovestu - 代码路上雾茫茫"
    },
    {
        "href":"https://landaiqing.space/",
        "cont":"QingYu-轻语博客"
    },
    {
        "href":"https://www.11zhang.com/",
        "cont":"十一张-爱生活，爱分享"
    },
    {
        "href":"https://www.chao6rj.top/",
        "cont":"超6软件"
    },

    {
        "href":"https://linux.do/t/topic/1051",
        "cont":"你们赢了，但我却没有输"
    },
    {
        "href":"https://fsoufsou.com/",
        "cont":"F搜索"
    },
    {
        "href":"https://ffsou.com/",
        "cont":"非凡搜索"
    },
    {
        "href":"https://g.luciaz.me/",
        "cont":"浙大镜像"
    },
    {
        "href":"https://search.essclick.com/",
        "cont":"essclick"
    },
    {
        "href":"https://search.fuyeor.com/zh-cn/Google",
        "cont":"search-fuyeor"
    },
    {
        "href":"https://fsoufsou.com/translate",
        "cont":"谷歌翻译"
    },
    {
        "href":"https://www.bootcdn.cn/",
        "cont":"bootcdn"
    },
    {
        "href":"https://www.runningcheese.com/",
        "cont":"奔跑中的奶酪"
    },
    {
        "href":"https://www.bmabk.com/index.php/post/73251.html",
        "cont":"A-moive|解决git clone 速度慢"
    },
    {
        "href":"https://iui.su/1492/",
        "cont":"不死鸟-网页在线工具汇总"
    },
    {
        "href":"https://www.nite07.com/u/nite07",
        "cont":"A-moive|Nite07小窝-资源下载"
    },

    {
        "href":"https://juejin.cn/post/7184720010563027001",
        "cont":"前端面试准备"
    },
    {
        "href":"https://qiushuizy.com/",
        "cont":"A-moive|秋水资源"
    },
//镜像站加速
// https://moeyy.cn/gh-proxy
// https://github.ur1.fun/
// https://ghps.cc/
// https://mirror.ghproxy.com/
// https://gh.ghproxy.com/
// https://ghproxy.homeboyc.cn/
// https://tool.mintimate.cn/gh/
// https://kkgithub.com/
// https://hub.yzuu.cf/
// https://hub.nuaa.cf/
// https://g.nite07.org
// git clone https://gitclone.com/github.com/javascript-tutorial/server
    {
        "href":"https://restars.co/",
        "cont":"橙子小栈"
    },
    {
        "href":"https://g.nite07.org/fastgh/fgit/releases",
        "cont":"fgit-github加速"
    },

    {
        "href":"https://agit.ai/",
        "cont":"Agit-面向AI发开者-代码托管服务"
    },
    {
        "href":"https://www.ittel.cn/",
        "cont":"技术之家"
    },
    {
        "href":"https://web.xml.wiki/",
        "cont":"网络搜索"
    },
    {
        "href":"http://www.rjzxw.com",
        "cont":"软件自学网"
    },
    {
        "href":"https://www.eslbuzz.com/",
        "cont":"英语学习神器"
    },
    {
        "href":"http://le.ouchn.cn/home",
        "cont":"国家终身教育平台"
    },
    {
        "href":"https://languangdao2.com/",
        "cont":"蓝光岛"
    },
    {
        "href":"https://alist.nn.ci/zh/",
        "cont":"Alist文档·网盘挂载"
    },
    {
        "href":"https://zhaoziyuan1.cc/",
        "cont":"找资源"
    },
    {
        "href":"http://tonkiang.us/",
        "cont":"IPTV搜索"
    },
    {
        "href":"https://www.8kmm.com/",
        "cont":"无锋网址导航"
    },
    {
        "href":"https://cn.bing.com/",
        "cont":"必应"
    },
    {
        "href":"https://letsbuild.ai/",
        "cont":"AI导航网站"
    },
    {
        "href":"https://github.com/jaywcjlove/DevHub",
        "cont":"DevHub"
    },
    {
        "href":"https://gpp.tkchu.me/acknowledgements.html",
        "cont":"游戏编程模式"
    },
    {
        "href":"https://aixdownloader.com/",
        "cont":"网页资源下载"
    },
    {
        "href":"https://aliso.cc/",
        "cont":"阿里搜"
    },
    {
        "href":"https://m3u.ibert.me/",
        "cont":"iptv-sources | Autoupdate iptv sources"
    },
    {
        "href":"https://quickref.cn/",
        "cont":"A-moive|开发人员·速查表 | Quick Reference"
    },
    {
        "href":"https://wordforest.cn/",
        "cont":"单词森林"
    },
    {
        "href":"https://word-wind.pages.dev/",
        "cont":"A-moive|单词之风"
    },
    {
        "href":"https://fzk.szlib.com/pc/home",
        "cont":"苏州图书馆·古籍数据库"
    },
    {
        "href":"https://melodis.co/zh",
        "cont":"AI·音乐"
    },
    {
        "href":"https://retardphobia.moebh.org/ui/index.html",
        "cont":"第十AI搜索"
    },
    {
        "href":"https://gitcode.com/",
        "cont":"GitCode - 开发者的代码家园"
    },
    {
        "href":"https://www.aplaybox.com/login",
        "cont":"模之屋·专业模型创作分享社区"
    },
    {
        "href":"https://www.blender.org/",
        "cont":"Free and Open 3D Creation Software"
    },
    {
        "href":"https://yunyinghui.feishu.cn/wiki/QrvDwaNt4icE2qkZTPSccNKInhh",
        "cont":"互联网知识地图"
    },
    {
        "href":"https://www.guwenshici.com/",
        "cont":"古文诗词·A"
    },
    {
        "href":"https://g.nite07.org/dxhuii?tab=repositories",
        "cont":"dxhuii"
    },
    {
        "href":"https://cms.im/",
        "cont":"内容清单·A"
    },
    {
        "href":"https://it-tools.tech/",
        "cont":"A-source|IT-TOOLS·助理开发人员和IT工作者·A"
    },
    {
        "href":"https://dxh.me/",
        "cont":"A-source|古文·古诗|Ding Xiao Hui-BLOG·A"
    },
    {
        "href":"https://github-rank.cms.im/",
        "cont":"Github Users Global Ranking·A"
    },
    {
        "href":"https://www.chatcns.cn/chat",
        "cont":"科研AI"
    },
    {
        "href":"https://www.arealme.com/cn",
        "cont":"A Real Me·arealme"
    },
    {
        "href":"https://iptv.vodtv.cn/",
        "cont":"IPTV.vodtv.cn"
    },
    {
        "href":"https://g.nite07.org/Tao-Boy/IPTV",
        "cont":"Tao-Boy-IPTV"
    },
    {
        "href":"https://3.jetbra.in/",
        "cont":"pycharm2021.3.1激活"
    },
    {
        "href":"https://www.jetbrains.com/pycharm/download/other.html",
        "cont":"pycharm-other-vision"
    },
    {
        "href":"https://gist.github.com/starred",
        "cont":"gist.github"
    },
    {
        "href":"https://software.3d66.com/",
        "cont":"3d66.com·软件下载"
    },
    {
        "href":"https://official.hideip.network/",
        "cont":"official.hideip.network"
    },
    {
        "href":"https://www.yutu.cn/",
        "cont":"A-moive|羽兔网·软件下载"
    },
    {
        "href":"https://paste.fastmirror.net/",
        "cont":"创建文档"
    },
    {
        "href":"https://www.modevol.com/",
        "cont":"渐构Modevol"
    },
    {
        "href":"https://jc.pep.com.cn/",
        "cont":"A-moive|中小学教材电子版"
    },
    {
        "href":"https://www.hifini.com/",
        "cont":"音乐"
    },
    {
        "href":"https://www.gequbao.com/",
        "cont":"歌曲宝"
    },
    {
        "href":"http://www.zzzdj.com/",
        "cont":"先上DJ·音乐网"
    },
    {
        "href":"https://www.kumeiwp.com/",
        "cont":"网盘共享·酷美网盘"
    },
    {
        "href":"https://www.kugeci.com/",
        "cont":"酷歌词·歌词"
    },
    {
        "href":"http://www.yinleku.cn/",
        "cont":"鑫巷子音乐酷"
    },
    {
        "href":"https://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/index.html",
        "cont":"R语言教程"
    },
    {
        "href":"https://www.jb51.net/javascript/306928jnd.htm",
        "cont":"pnpm"
    },
    {
        "href":"https://zhuanlan.zhihu.com/p/546400909",
        "cont":"新一代包管理工具 pnpm 使用心得"
    },
    {
        "href":"https://pnpm.io/zh/cli/install",
        "cont":"pnpm install | pnpm"
    },
    {
        "href":"https://metaso.cn/",
        "cont":"秘塔AI搜索·AAAAA"
    },
    {
        "href":"https://janereader.com/",
        "cont":"Jane Reader-现代化的 epub 阅读器"
    },
    {
        "href":"https://video.451024.xyz/",
        "cont":"影视搜索"
    },
    {
        "href":"https://meta.appinn.net/",
        "cont":"小众软件"
    },
    {
        "href":"https://www.douyin.com/user/MS4wLjABAAAAI6H96BAtp7k8T6MI1tnMXMCAlpGAuiW6ucRHTYewFso",
        "cont":"画画的妮妮"
    },
    {
        "href":"https://996.ninja/",
        "cont":"摸鱼"
    },
    //2024.05.11 资源搜索引擎
    {
        "href":"https://yandex.com/",
        "cont":"搜索引擎"
    },
    {
        "href":"https://thinkany.so/zh",
        "cont":"thinkany"
    },
    {
        "href":"https://iui.su/3700/",
        "cont":"资源搜索引擎"
    },
    {
        "href":"https://www.tiangong.cn/",
        "cont":"天工AI"
    },
    {
        "href":"https://retardphobia.moebh.org/ui/index.html",
        "cont":"十号AI搜索"
    },
    {
        "href":"https://metaso.cn/",
        "cont":"秘塔AI搜索"
    },
    {
        "href":"https://cn.bing.com/",
        "cont":"必应"
    },
    {
        "href":"https://ali.gitcafe.ink/",
        "cont":"小纸条·网盘资源搜索"
    },
    {
        "href":"https://hematown.com/",
        "cont":"河马小镇·AI"
    },
    {
        "href":"https://www.pansou.vip/",
        "cont":"盘搜"
    },
    {
        "href":"https://official.hideip.network/",
        "cont":"official.hideip.network"
    },
    {
        "href":"https://www.4kvm.pro",
        "cont":"4kvm.pro"
    },
    {
        "href":"http://www.bookxnote.com/",
        "cont":"epub电子书阅读"
    },
    {
        "href":"https://g.nite07.org/it-ebooks-0",
        "cont":"计算机电子书"
    },
    {
        "href":"https://www.ppbzy.com/",
        "cont":"白噪音·助眠"
    },
    {
        "href":"https://markdown-editor.org/",
        "cont":"markdown-editor-在线编辑器"
    },
    {
        "href":"https://ssn.chatyy.org/",
        "cont":"ChatAI"
    },
    {
        "href":"https://hotkeycheatsheet.com/zh",
        "cont":"快捷键备忘录"
    },
    //清华大学
    {
        "href":"https://www.xuetangx.com",
        "cont":"学堂在线·清华"
    },
    {
        "href":"https://www.shenyandayi.com",
        "cont":"深言达意·清华"
    },
    {
        "href":"https://ijiaodui.com",
        "cont":"i校对·清华"
    },
    {
        "href":"https://jiuge.thunlp.org",
        "cont":"九歌·清华"
    },
    {
        "href":"https://www.shengshu-ai.com/home?ref=maginative.com",
        "cont":"Vidu·清华"
    },
    // 北京大学
    {
        "href":"https://www.chatlaw.cloud",
        "cont":"chatlaw·北大"
    },
    {
        "href":"https://renwuzhi.wiki",
        "cont":"中国历代人物·北大"
    },
    {
        "href":"https://chatexcel.com",
        "cont":"chatexcel·北大"
    },
    {
        "href":"https://www.chinesemooc.org",
        "cont":"华文慕课·北大"
    },
    {
        "href":"https://pup6.yunzhan365.com/bookcase/jmyr/index.html",
        "cont":"北大出版社电子书架·北大"
    },
    {
        "href":"https://www.shidianguji.com",
        "cont":"识典古籍·北大"
    },
    //复旦大学
    {
        "href":"https://github.com/OpenMOSS/MOSS?tab=readme-ov-file",
        "cont":"MOSS·复旦"
    },
    {
        "href":"http://mousi.org",
        "cont":"听见世界·复旦"
    },
    {
        "href":"https://github.com/lzw-lzw/GroundingGPT",
        "cont":"LEGO·复旦"
    },
    // 华东师范大学
    {
        "href":"https://elion.ecnu.edu.cn",
        "cont":"小花狮·华东"
    },
    // 北师大
    {
        "href":"https://aitools.bnu.edu.cn",
        "cont":"AI工具·北师大"
    },
    {
        "href":"https://aic-fe.bnu.edu.cn/ai_teacher/",
        "cont":"AI好老师·北师大"
    },
    // 香港大学
    {
        "href":"https://damo-vilab.github.io/AnyDoor-Page/",
        "cont":"anydoor·港大"
    },
    {
        "href":"https://www.usenix.org/conference/usenixsecurity23/presentation/ni",
        "cont":"app listener·港大"
    },
    //content
    {
        "href":"https://paste.fastmirror.net/",
        "cont":"A-moive|创建文档"
    },
    {
        "href":"https://www.modevol.com/",
        "cont":"A-moive|渐构Modevol"
    },
    {
        "href":"https://hellogithub.com/",
        "cont":"HelloGithub"
    },
    {
        "href":"https://www.gaoding.com/",
        "cont":"稿定设计"
    },
    {
        "href":"https://app.lighttools.net/",
        "cont":"轻兔推荐"
    },
    {
        "href":"https://geekcard.app/",
        "cont":"卡片文字"
    },
    {
        "href":"https://latentbox.com/zh",
        "cont":"Latent Box·AAAAA"
    },
    {
        "href":"https://hellowindows.cn/",
        "cont":"windows软件·AAAAA"
    },
    {
        "href":"https://www.52pojie.cn/thread-1933348-1-1.html",
        "cont":"电脑需要重装"
    },
    {
        "href":"https://jc.pep.com.cn/",
        "cont":"中小学教材电子版"
    },
    {
        "href":"https://www.xxx5217.com/",
        "cont":"5217·游戏资源"
    },
    {
        "href":"https://eternallybored.org/misc/wget/",
        "cont":"wget·download"
    },
    {
        "href":"https://kaisouai.com/",
        "cont":"开搜·AI"
    },
    {
        "href":"https://www.toolskithub.com/zh-CN",
        "cont":"ToolsKithub | 在线工具站 "
    },
    {
        "href":"https://chattts.lingandata.com/",
        "cont":"ChatTTS中文版"
    },
    {
        "href":"https://polaroidy.iwhy.dev/generator",
        "cont":"极简边框"
    },
    {
        "href":"https://tools.fastmirror.net/",
        "cont":"工具 | FastMirror"
    },
    {
        "href":"https://chilisou15.xyz/",
        "cont":"池里搜·资源搜索"
    },
    {
        "href":"https://www.indiehackers.site/zh/group/new",
        "cont":"开发者导航"
    },
    {
        "href":"https://textbook.synaiv.com/",
        "cont":"教材下载工具"
    },
    {
        "href":"https://so.nuu.su/",
        "cont":"YUNYAN-Search·搜索引擎"
    },
    {
        "href":"https://www.oschina.net/group/fishfish",
        "cont":"摸鱼专区"
    },
    {
        "href":"https://www.meijian.com/e-commerce",
        "cont":"AI创意商拍"
    },
    {
        "href":"https://blog.wfso.cn/archives/115/",
        "cont":"实用软件"
    },
    {
        "href":"https://www.right.com.cn/forum/",
        "cont":"恩山论坛"
    },
    {
        "href":"http://www.doyoudo.com",
        "cont":"多媒体"
    },
    {
        "href":"https://www.ygxz.in/",
        "cont":"小站之外"
    },
    {
        "href":"https://dh.echs.top/",
        "cont":"自用导航"
    },
    {
        "href":"https://echs.top/",
        "cont":"主页 | ECHSFXYA"
    },
    {
        "href":"https://echs.top/%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5",
        "cont":"友情链接"
    },
    {
        "href":"https://www.imets.cn/",
        "cont":"静若安然"
    },
    {
        "href":"https://www.wxy97.com/archives/20",
        "cont":"我的常用软件"
    },
    {
        "href":"https://www.aisourcehub.info/",
        "cont":"AI科技·信息源"
    },
    {
        "href":"https://mirrors.tuna.tsinghua.edu.cn/",
        "cont":"清华大学开源镜像"
    },
    //2024.06.25
    {
        "href":"https://z.etocs.us.kg/",
        "cont":"电子书下载"
    },
    {
        "href":"https://jpom.top/",
        "cont":"Jpom项目运维"
    },
    {
        "href":"https://yunpan8.cc/",
        "cont":"云盘吧"
    },
    {
        "href":"http://v.kepu.net.cn/mooc/qb/",
        "cont":"中国科普博览"
    },
    {
        "href":"https://pubscholar.cn/",
        "cont":"PubScholar公益学术平台"
    },
    //2024.06.29
    {
        "href":"https://zzz.mihoyo.com/main",
        "cont":"绝区零"
    },
    {
        "href":"https://zsk.ai/home",
        "cont":"A-moive|发现优秀的知识库"
    },
    {
        "href":"https://www.opkfc.com/list",
        "cont":"A-moive|数字玩家·ChatGPT账号"
    },
    {
        "href":"https://666666.dev/#/",
        "cont":"A-moive|IT人必备工具箱"
    },
    {
        "href":"https://www.qqyin.com/",
        "cont":"A-moive|QQ音速网"
    },
    {
        "href":"https://www.wxy97.com/archives/0248581d-12c6-4468-a04f-c8824faa7118",
        "cont":"Java知识库网站收集整理"
    },
    {
        "href":"https://www.hello-algo.com/",
        "cont":"Hello 算法"
    },
    {
        "href":"http://hpc.ncpgr.cn/",
        "cont":"作重计算平台用户手册"
    },
    {
        "href":"http://svip.zhuiying.cyou/",
        "cont":"A-moive|追影视频"
    },
    //2024.07.08
    {
        "href":"https://www.okday.app/",
        "cont":"日记软件"
    },
    {
        "href":"https://mumingfang.com/",
        "cont":"创意坊|霂明坊"
    },
    {
        "href":"https://www.ahhhhfs.com/60035/",
        "cont":"ChatGPT+MJ+SD – AIGC专题"
    },
    {
        "href":"https://so.gitee.com/",
        "cont":"Gitee Search - 开源软件搜索"
    },
    {
        "href":"https://js.okten.cn/",
        "cont":"《JavaScript 权威指南第七版》中英对照"
    },
    {
        "href":"https://keai.cm/",
        "cont":"A-moive|可爱TV"
    },
    {
        "href":"https://laozhaopianai.com/",
        "cont":"AI老照片生成器"
    },
    {
        "href":"https://klingai.kuaishou.com/",
        "cont":"可灵AI-新一代AI创意生产力平台"
    },
    {
        "href":"https://zh.annas-archive.li/",
        "cont":"安娜的档案|图书下载"
    },
    {
        "href":"https://mgb.abyssdawn.com/#/index",
        "cont":"情报主页-魔盒"
    },
    {
        "href":"https://tophub.today/c/blog",
        "cont":"A-moive|今日热榜·专栏"
    },
    {
        "href":"https://techbrood.com/",
        "cont":"踏得|沉浸式互联网体验和学习门户"
    },
    {
        "href":"https://www.sass.hk/docs/",
        "cont":"Sass中文网|SCSS"
    },
    {
        "href":"https://kspider.kangert.top/",
        "cont":"在线可视化爬虫平台"
    },
    {
        "href":"https://ejsoon.win/",
        "cont":"A-moive|天蒼人頡–發掘好玩事物"
    },
    {
        "href":"https://vvyst0z7tes.feishu.cn/wiki/HQuawZepyiwNiNkImw6c00IXnmc",
        "cont":"英语提升指南"
    },
    {
        "href":"https://flix.center/",
        "cont":"Flix快传"
    },
    {
        "href":"https://book-db-v1.saltyleo.com/",
        "cont":"A-moive|SaltyLeo的图书元数据API"
    },
    {
        "href":"https://book.tstrs.me/",
        "cont":"A-moive|SaltyLeo的书架|图书搜索"
    },
    {
        "href":"https://saltyleo.com/",
        "cont":"A-moive|SaltyLeo的博客"
    },
    {
        "href":"https://www.koodoreader.com/zh",
        "cont":"A-moive|开源电子阅读|koodo-reader"
    },
    // 2024.07.19
    {
        "href":"https://photo2poem.top/",
        "cont":"诗境 - 通过AI为照片匹配诗句，生成分享卡片"
    },
    {
        "href":"https://hanfu.in/",
        "cont":"汉服网"
    },
    {
        "href":"https://aliyunpan1.com/",
        "cont":"A-moive|阿里云盘资源论坛"
    },
    {
        "href":"https://chat18.aichatos8.com/#/chat/1721573199345",
        "cont":"AAA-moive|AI·chatOS"
    },
    {
        "href":"https://www.lengcat.cn/",
        "cont":"AAA-moive|冷猫导航站"
    },
    {
        "href":"https://www.j00j.com/",
        "cont":"A-moive|美剧网"
    },
    {
        "href":"https://tool.lu/mine/",
        "cont":"A-moive|在线工具"
    },
    {
        "href":"https://n.mumingfang.com/ai",
        "cont":"A-moive|AI网址导航"
    },
    {
        "href":"https://jetbrains.asiones.com/",
        "cont":"JetBrains 系列全家桶激活服务器"
    },
    {
        "href":"https://shdpyq.com/",
        "cont":"天天影视"
    },
    {
        "href":"https://chat.moyanaigc.com/#/sceneModel/work",
        "cont":"A-moive|工作台-陌言"
    },
    {
        "href":"https://urlapp.org/apps/app2024072200006/2048game",
        "cont":"A-moive|2048小游戏"
    },
    {
        "href":"https://play2048.co/",
        "cont":"A-moive|2048小游戏"
    },
    {
        "href":"https://www.islide.cc/",
        "cont":"iSlide-PPT模板下载平台"
    },
    {
        "href":"https://meta.appinn.net/",
        "cont":"小众软件论坛"
    },
    {
        "href":"https://music.wandhi.com/",
        "cont":"music_download"
    },
    {
        "href":"https://chandler.bet/#/overView",
        "cont":"ai|chandler"
    },
    {
        "href":"https://tmioe.com/",
        "cont":"ZAPRO·杂铺-高质量影视资讯与技术分享平台"
    },
    {
        "href":"https://zeabur.com/zh-CN",
        "cont":"Zeabur-Deploy Painlessly,Scale Infinitely"
    },
    {
        "href":"http://www.cuishuaiwen.com:8000/zh/",
        "cont":"A-moive|Eureka"
    },
    {
        "href":"http://www.cuishuaiwen.com:8000/zh/PROJECT/TECH-BLOG/mkdocs_and_material/",
        "cont":"使用MkDocs和Material主题搭建技术博客"
    },
    {
        "href":"https://www.mkdocs.org/",
        "cont":"mkdocs"
    },
    {
        "href":"https://michael18811380328.github.io/",
        "cont":"A-moive|michael18811380328"
    },
    {
        "href":"https://markdown-docs-zh.readthedocs.io/zh-cn/latest/",
        "cont":"A-moive|MkDocs 中文文档"
    },
    {
        "href":"https://mydramalist.com/",
        "cont":"MyDramalist-亚洲影视资讯平台"
    },
    {
        "href":"https://alphacoders.com/",
        "cont":"Alpha Coders-Wallpapers"
    },
    {
        "href":"https://wangchujiang.com/free-font/",
        "cont":"商用免费字体"
    },
    {
        "href":"https://minsonlee.github.io",
        "cont":"minsonlee"
    },
    {
        "href":"https://www.rikua.com/",
        "cont":"字幕下载"
    },
    {
        "href":"https://3.jetbra.in/",
        "cont":"Jetbrains激活码地址"
    },
    //2024.08.01
    {
        "href":"https://nowhots.com/",
        "cont":"A-moive|即时热点"
    },
    {
        "href":"https://qianp.com/",
        "cont":"A-moive|千篇网"
    },
    {
        "href":"https://source.zgqinc.gq/",
        "cont":"A-moive|各种源大型整合"
    },
    {
        "href":"https://www.napkin.ai/",
        "cont":"A-moive|AI将文字转可视化"
    },
    {
        "href":"https://xiaodundun.net/",
        "cont":"A-moive|攒劲小蹲蹲"
    },
    {
        "href":"https://thoughts.teambition.com/share/63e49fc707956f0045d3ebbc",
        "cont":"英语学习"
    },
    {
        "href":"https://pan.fccp.in/",
        "cont":"A-source|FCCP网盘"
    },
    {
        "href":"https://www.aliyundrive.com/s/j7Z6PsXgDxv",
        "cont":"DK-英语"
    },
    {
        "href":"https://vk.com/wall534911818_2103",
        "cont":"A-source|DK-英语"
    },
    {
        "href":"https://z-lib.id/",
        "cont":"ebook-download"
    },
    {
        "href":"https://gutenberg.org/",
        "cont":"A-source|Ebooks-search"
    },
    {
        "href":"https://daohangxie.com/",
        "cont":"导航蟹"
    },
    {
        "href":"https://media.zidi.me/%E7%94%B5%E8%A7%86%E5%89%A7/%E6%B8%AF%E5%8F%B0/TVB/%E7%BB%8F%E5%85%B8%E6%AD%A6%E4%BE%A0%E5%89%A7/%E9%87%91%E5%BA%B8/%E3%80%9001%E3%80%91%E9%9B%AA%E5%B1%B1%E9%A3%9E%E7%8B%90.1985",
        "cont":"A-source|小姐姐的仓库"
    },
    {
        "href":"https://media.zidi.me/",
        "cont":"A-source|小姐姐的仓库"
    },
    {
        "href":"https://www.icourse163.org/",
        "cont":"中国大学MOOC"
    },
    {
        "href":"https://4275.com/",
        "cont":"免登录网盘"
    },
    {
        "href":"https://dl.askk.cc/cmcc",
        "cont":"cmcc | Sukanka 的仓库cpa"
    },
    {
        "href":"https://zxcs.dmnb.cf/",
        "cont":"cmcc | Sukanka 的仓库cpb"
    },
    {
        "href":"https://zxcs.4everland.app/#/",
        "cont":"cmcc | Sukanka 的仓库cpc"
    },
    {
        "href":"https://tianya.at/?s=reload",
        "cont":"天涯神贴"
    },
    {
        "href":"https://ueg.cc/",
        "cont":"文本处理器"
    },
    {
        "href":"https://ilovejigsaw.com/",
        "cont":"A-moive|拼图"
    },
    {
        "href":"https://siliconcat.net/",
        "cont":"硅猫 SoC|计算机参数"
    },
    {
        "href":"https://public.work/",
        "cont":"A-moive|无版权图库"
    },
    {
        "href":"https://yan.ognai.com/",
        "cont":"A-moive|颜语"
    },
    {
        "href":"https://snaptik.biz/zh-cn",
        "cont":"A-moive|youtube-download"
    },
    {
        "href":"https://www.kumeiwp.com/",
        "cont":"A-moive|酷美网盘"
    },
    {
        "href":"https://www.gfxtra31.com/",
        "cont":"A-moive|gfxtra31.proxy"
    },
    {
        "href":"https://pan.baidu.com/s/12J7mt6fuwmrCkVgNn4xWAQ?pwd=cbm6",
        "cont":"A-source|DK-英语"
    },
    {
        "href":"https://www.douban.com/",
        "cont":"豆瓣网"
    },
    {
        "href":"https://zhale.me/",
        "cont":"A-source|网络拨测工具"
    },
    {
        "href":"https://vercel.com/signup",
        "cont":"vercel.com"
    },
    {
        "href":"https://whoer.com/zh/",
        "cont":"A-source|IP地址查询"
    },
    {
        "href":"https://www.hou4.com/",
        "cont":"A-source|软件大全"
    },
    {
        "href":"https://www.fang1688.cn/",
        "cont":"方包博客"
    },
    {
        "href":"https://johnserf-seed.github.io/f2/",
        "cont":"A-moive|Fast 2 EveryFast 2 Every"
    },
    {
        "href":"https://gotranscript.com/subtitle-converter",
        "cont":"A-soure字幕转换"
    },
    {
        "href":"https://www.cnblogs.com/wpjamer",
        "cont":"wpjamer"
    },
    {
        "href":"https://z.etocs.us.kg/",
        "cont":"电子书下载"
    },
    {
        "href":"https://jpom.top/",
        "cont":"Jpom项目运维"
    },
    {
        "href":"https://yunpan8.cc/",
        "cont":"云盘吧·AAAAA"
    },
    {
        "href":"http://v.kepu.net.cn/mooc/qb/",
        "cont":"中国科普博览"
    },
    {
        "href":"https://pubscholar.cn/",
        "cont":"PubScholar公益学术平台"
    },
    {
        "href":"https://music.bestgeek.org/#/",
        "cont":"极客音乐"
    },
    {
        "href":"https://zzz.mihoyo.com/main",
        "cont":"绝区零"
    },
    {
        "href":"https://zsk.ai/home",
        "cont":"发现优秀的知识库"
    },
    {
        "href":"https://www.opkfc.com/list",
        "cont":"数字玩家·ChatGPT账号"
    },
    {
        "href":"https://666666.dev/#/",
        "cont":"IT人必备工具箱·AAAAA"
    },
    {
        "href":"https://www.qqyin.com/",
        "cont":"QQ音速网"
    },
    {
        "href":"https://www.wxy97.com/archives/0248581d-12c6-4468-a04f-c8824faa7118",
        "cont":"Java知识库网站收集整理 | AAAAA"
    },
    {
        "href":"https://www.hello-algo.com/",
        "cont":"Hello 算法 | AAAAA"
    },
    {
        "href":"http://hpc.ncpgr.cn/",
        "cont":"作重计算平台用户手册 | AAAAA"
    },
    {
        "href":"http://zhuiying.cc/",
        "cont":"追影TV"
    },
    {
        "href":"https://www.okday.app/",
        "cont":"日记软件"
    },
    {
        "href":"https://mumingfang.com/",
        "cont":"创意坊|霂明坊"
    },
    {
        "href":"https://www.ahhhhfs.com/60035/",
        "cont":"ChatGPT+MJ+SD – AIGC专题"
    },
    {
        "href":"https://so.gitee.com/",
        "cont":"Gitee Search - 开源软件搜索"
    },
    {
        "href":"https://js.okten.cn/",
        "cont":"《JavaScript 权威指南第七版》中英对照"
    },
    {
        "href":"https://keai.cm/",
        "cont":"可爱TV|AAAAA"
    },
    {
        "href":"https://laozhaopianai.com/",
        "cont":"AI老照片生成器"
    },
    {
        "href":"https://klingai.kuaishou.com/",
        "cont":"可灵AI-新一代AI创意生产力平台"
    },
    {
        "href":"https://zh.annas-archive.li/",
        "cont":"安娜的档案|图书下载"
    },
    {
        "href":"https://mgb.abyssdawn.com/#/index",
        "cont":"情报主页-魔盒"
    },
    {
        "href":"https://tophub.today/c/blog",
        "cont":"今日热榜|专栏·AAAAA"
    },
    {
        "href":"https://techbrood.com/",
        "cont":"踏得|沉浸式互联网体验和学习门户"
    },
    {
        "href":"https://www.sass.hk/docs/",
        "cont":"Sass中文网|SCSS"
    },
    {
        "href":"https://kspider.kangert.top/",
        "cont":"在线可视化爬虫平台"
    },
    {
        "href":"https://wusunk.com/",
        "cont":"无损库资源|music"
    },
    {
        "href":"https://www.yintu.me/",
        "cont":"音兔无损|music"
    },
    {
        "href":"https://ejsoon.win/",
        "cont":"A-source|天蒼人頡–發掘好玩事物"
    },
    {
        "href":"https://vvyst0z7tes.feishu.cn/wiki/HQuawZepyiwNiNkImw6c00IXnmc",
        "cont":"英语提升指南"
    },
    {
        "href":"https://flix.center/",
        "cont":"Flix快传"
    },
    {
        "href":"https://book-db-v1.saltyleo.com/",
        "cont":"SaltyLeo 的图书元数据 API|AAAAA"
    },
    {
        "href":"https://book.tstrs.me/",
        "cont":"SaltyLeo的书架|图书搜索|AAAA"
    },
    {
        "href":"https://saltyleo.com/",
        "cont":"SaltyLeo的博客|AAAA"
    },
    {
        "href":"https://www.koodoreader.com/zh",
        "cont":"A-source|开源电子阅读|koodo-reader"
    },
    {
        "href":"https://photo2poem.top/",
        "cont":"诗境 - 通过AI为照片匹配诗句，生成分享卡片"
    },
    {
        "href":"https://hanfu.in/",
        "cont":"汉服网"
    },
    {
        "href":"https://aliyunpan1.com/",
        "cont":"A-source|阿里云盘资源论坛"
    },
    {
        "href":"https://chat18.aichatos8.com/#/chat/1721573199345",
        "cont":"AAA-source|AI·chatOS"
    },
    {
        "href":"https://www.lengcat.cn/",
        "cont":"AAA-source|冷猫导航站"
    },
    {
        "href":"https://www.j00j.com/",
        "cont":"A-source|美剧网"
    },
    {
        "href":"https://tool.lu/mine/",
        "cont":"A-source|在线工具"
    },
    {
        "href":"https://n.mumingfang.com/ai",
        "cont":"A-source|AI网址导航"
    },
    {
        "href":"https://jetbrains.asiones.com/",
        "cont":"JetBrains 系列全家桶激活服务器"
    },
    {
        "href":"https://shdpyq.com/",
        "cont":"天天影视"
    },
    {
        "href":"https://chat.moyanaigc.com/#/sceneModel/work",
        "cont":"A-source|工作台-陌言"
    },
    {
        "href":"https://urlapp.org/apps/app2024072200006/2048game",
        "cont":"A-source|2048小游戏"
    },
    {
        "href":"https://play2048.co/",
        "cont":"A-source|2048小游戏"
    },
    {
        "href":"https://www.islide.cc/",
        "cont":"iSlide-PPT模板下载平台"
    },
    {
        "href":"https://meta.appinn.net/",
        "cont":"小众软件论坛"
    },
    {
        "href":"https://music.wandhi.com/",
        "cont":"music_download"
    },
    {
        "href":"https://chandler.bet/#/overView",
        "cont":"ai|chandler"
    },
    {
        "href":"https://tmioe.com/",
        "cont":"ZAPRO·杂铺-高质量影视资讯与技术分享平台"
    },
    {
        "href":"https://zeabur.com/zh-CN",
        "cont":"Zeabur-Deploy Painlessly,Scale Infinitely"
    },
    {
        "href":"http://www.cuishuaiwen.com:8000/zh/",
        "cont":"A-source|Eureka"
    },
    {
        "href":"http://www.cuishuaiwen.com:8000/zh/PROJECT/TECH-BLOG/mkdocs_and_material/",
        "cont":"使用MkDocs和Material主题搭建技术博客"
    },
    {
        "href":"https://www.mkdocs.org/",
        "cont":"mkdocs"
    },
    {
        "href":"https://michael18811380328.github.io/",
        "cont":"A-source|michael18811380328"
    },
    {
        "href":"https://markdown-docs-zh.readthedocs.io/zh-cn/latest/",
        "cont":"A-source|MkDocs 中文文档"
    },
    {
        "href":"https://mydramalist.com/",
        "cont":"MyDramalist-亚洲影视资讯平台"
    },
    {
        "href":"https://alphacoders.com/",
        "cont":"Alpha Coders-Wallpapers"
    },
    {
        "href":"https://wangchujiang.com/free-font/",
        "cont":"商用免费字体"
    },
    {
        "href":"https://minsonlee.github.io",
        "cont":"minsonlee"
    },
    {
        "href":"https://www.rikua.com/",
        "cont":"字幕下载"
    },
    {
        "href":"https://3.jetbra.in/",
        "cont":"Jetbrains激活码地址"
    },
    {
        "href":"https://www.xzbzq.com/",
        "cont":"学子备战墙"
    },
    {
        "href":"https://iui.su/hot/",
        "cont":"A-source|search"
    },
    {
        "href":"https://yyjingyan.com/",
        "cont":"有用经验"
    },
    {
        "href":"https://www.maokan.cc/",
        "cont":"A-source|白噪音"
    },
    {
        "href":"https://datong.io/ui/index.html",
        "cont":"大同搜索"
    },
    {
        "href":"https://9.234456.xyz/abc.html?t=567",
        "cont":"V2RAY"
    },
    {
        "href":"https://git.zx2c4.com/wireguard-windows",
        "cont":"wireguard-mirror"
    },
    {
        "href":"https://v2rayn.org/",
        "cont":"最新 v2rayN 使用教程快速入门篇"
    },
    {
        "href":"https://blog.starryvoid.com/archives/337.html",
        "cont":"WireGuard 搭建方法与使用教程"
    },
    {
        "href":"https://www.vumstar.com/",
        "cont":"vum星球"
    },
    {
        "href":"https://github.com/GFW-knocker/MahsaNG.git",
        "cont":"A-source|MahsaNG|online"
    },
    {
        "href":"https://github.com/chen08209/FlClash.git",
        "cont":"FlClash"
    },
    {
        "href":"https://kjgx668.blogspot.com/2024/07/2024vpnflclashwindowswindowslinuxmacos.html",
        "cont":"FlClash-BLOG"
    },
    {
        "href":"https://favorites.pages.dev/new",
        "cont":"A-source|收藏"
    },
    {
        "href":"https://www.gitbook.com/",
        "cont":"GitBook"
    },
    {
        "href":"https://appsj.szxuexiao.com/",
        "cont":"小学试卷网"
    },
    {
        "href":"https://w2.apachecn.org/",
        "cont":"A-source|组织云盘合集"
    },
    {
        "href":"https://www.kejixiaolu.com/index.html",
        "cont":"科技小露·科学上网"
    },
    {
        "href":"https://kji.gitbook.io/vn",
        "cont":"2024·科学上网"
    },
    {
        "href":"https://kejilion.blogspot.com/",
        "cont":"科技blog"
    },
    {
        "href":"https://www.trancy.org/",
        "cont":"trancy"
    },
    {
        "href":"https://css.bqrdh.com/cdn/hub",
        "cont":"选取最优 cdn"
    },
    {
        "href":"https://ittools.cc/",
        "cont":"工具网址导航"
    },
    {
        "href":"http://yydsvip.ysepan.com/",
        "cont":"A-source|资源集"
    },
    {
        "href":"https://www.wanrenmi8.com/cn/index.html",
        "cont":"A-source|云盘导航"
    },
    {
        "href":"https://tuostudy.upnb.top/",
        "cont":"A-source|图欧学习导航"
    },
    {
        "href":"https://iui.su/3093/",
        "cont":"发现有趣的东西"
    },
    {
        "href":"https://ilingban.com/",
        "cont":"灵办AI"
    },
    {
        "href":"https://cjkgirls.com/",
        "cont":"瀑布流美女分享"
    },
    {
        "href":"https://tts.femoon.top/cn",
        "cont":"A-source|Azure Text To Speech(TTS)|语音生成TTS"
    },
    {
        "href":"https://502book.com/",
        "cont":"A-source|502book小说"
    },
    {
        "href":"https://www.talktalkai.com/",
        "cont":"A-source|AI·音乐"
    },
    {
        "href":"https://npm.io/",
        "cont":"A-source|npm包搜索"
    },
    {
        "href":"https://hot.ittools.cc/#/",
        "cont":"A-source|今日热榜"
    },
    {
        "href":"https://www.coze.cn/",
        "cont":"扣子-AI智能体开发平台"
    },
    {
        "href":"https://copilot.microsoft.com/",
        "cont":"copilot·AI助手"
    },
    {
        "href":"https://www.freedidi.com/",
        "cont":"A-source|零度解说freedidi"
    },
    {
        "href":"https://urlapp.org/apps/app2024072500021/tetris-min",
        "cont":"俄罗斯方块"
    },
    {
        "href":"https://classcms.com/",
        "cont":"内容管理系统"
    },
    {
        "href":"https://blog.fjy.zone/",
        "cont":"IT知识空间"
    },
    {
        "href":"https://youtube.iiilab.com/",
        "cont":"A-source|youtube-video-download"
    },
    {
        "href":"http://www.potplayercn.com/course/2982.html",
        "cont":"PotPlayer中文网"
    },
    {
        "href":"2a09:bac5:638c:1250::1d3:22",
        "cont":"google-search"
    },
    {
        "href":"https://freetts.com",
        "cont":"A-source|freetts-TTS"
    },
    {
        "href":"https://ondoku3.com/zh-hans/",
        "cont":"ondoku3-TTS"
    },
    {
        "href":"https://www.xaudiopro.com/aivoice/",
        "cont":"XAudioPro-TTS"
    },
    {
        "href":"https://zenvideo.qq.com/",
        "cont":"腾讯智影-TTS"
    },
    {
        "href":"https://www.gamersky.com/tools/map/wukong/?mapId=48",
        "cont":"黑神话·悟空"
    },
    {
        "href":"https://diffsuite.com/",
        "cont":"文本对比工具"
    },
    {
        "href":"https://bbs.tatans.cn/topic/tag/%E9%9F%B3%E4%B9%90%E5%88%86%E4%BA%AB",
        "cont":"音乐分享"
    },
    {
        "href":"https://www.jihuola.cn/idea99.html",
        "cont":"激活"
    },
    {
        "href":"https://urlyzer.com/zh/get-metadata-from-url",
        "cont":"网站元数据提取器"
    },
    {
        "href":"https://www.freedidi.com/11958.html",
        "cont":"ChatGPT·零度解说"
    },
    {
        "href":"https://chatgpt.com/",
        "cont":"chatGPT"
    },
    {
        "href":"https://new.cherrychat.org/auth/register?inviteCode=H2GBMPNFL",
        "cont":"樱桃茶·智域GPT"
    },
    {
        "href":"https://freemp3cn.com/#/",
        "cont":"A-source|freemp3"
    },
    {
        "href":"https://xiayibendushenme.com/",
        "cont":"下一本读什么"
    },
    {
        "href":"https://cloudtts.com/",
        "cont":"cloudtts"
    },
    {
        "href":"https://stackblitz.com/",
        "cont":"A-source|StackBlitz"
    },
    {
        "href":"https://tools.liumingye.cn/music/#/",
        "cont":"音乐·tools"
    },
    {
        "href":"https://piano.bqrdh.com/#/",
        "cont":"钢琴online"
    },
    {
        "href":"https://stranslate.zggsong.com/",
        "cont":"A-source|STranslate"
    },
    {
        "href":"https://pdai.tech/md/resource/tools.html",
        "cont":"A-source|资源导航"
    },
    {
        "href":"https://mdgjx.com/",
        "cont":"开源工具箱"
    },
    {
        "href":"https://vultr.youmu.moe/quiz/",
        "cont":"中国省级行政区划小测试"
    },
    {
        "href":"https://24hbook.com/",
        "cont":"A-source|24h搜书"
    },
    {
        "href":"https://babyno.top/",
        "cont":"A-source|路边的阿布"
    },
    {
        "href":"https://www.bttwo.org/",
        "cont":"A-source|BT下载和分享"
    },

    //2024.10.09
    {
		"href":"/website/web_collect/source/pwd.html",
		"cont":"pwd"
	},
    {
		"href":"",
		"cont":""
	},
    {
		"href":"",
		"cont":""
	},
    {
		"href":"",
		"cont":""
	},
    {
		"href":"",
		"cont":""
	},
    {
		"href":"",
		"cont":""
	},
];
